version: "3.8"

services:
  secret-gen-client:
    build:
      context: ./client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - secret-gen-server
    networks:
      - app-network
    container_name: secret-gen-client

  secret-gen-server:
    build:
      context: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - HOSTNAME=0.0.0.0
    networks:
      - app-network
    container_name: secret-gen-server

networks:
  app-network:
    driver: bridge
