version: "3.8"

services:
  client:
    build:
      context: ./client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - server

  server:
    build:
      context: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      HOSTNAME: "0.0.0.0"
